export enum Language {
    PUSH = "PUSH",
    LOAD = "LOAD",
    STORE = "STORE",
    POP = "POP",
    DUP = "DUP",
    ADD = "ADD",
    SUB = "SUB",
    DIV = "DIV",
    MUL = "MUL",
    IN = "IN",
    OUT = "OUT",
    AND = "AND",
    OR = "OR",
    NOT = "NOT",
    GT = "GT",
    LT = "LT",
    GE = "GE",
    LE = "LE",
    EQ = "EQ",
    NE = "NE",
    NOP = "NOP",
    WHITE_LINE = "",
    HALT = "HALT"
}